models/Employees.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "employees".
 *
 * @property int $id
 * @property string $name
 *
 * @property Terminals[] $terminals
 * @property Subdivisions $subdivisions
 */
class Employees extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'employees';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['subdivisions_id'], 'exist', 'skipOnError' => true, 'targetClass' => Subdivisions::className(), 'targetAttribute' => ['subdivisions_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'subdivisions_id' => 'Отделение',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTerminals()
    {
        return $this->hasMany(Terminals::className(), ['employees_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubdivisions()
    {
        return $this->hasOne(Subdivisions::className(), ['id' => 'subdivisions_id']);
    }

    public function getSubdivisionsWithTerminalCount(){
        $result = Terminals::find()
            ->select(['s.name, COUNT(*) as c'])
            ->from('terminals t')
            ->join('LEFT JOIN','subdivisions s','t.subdivisions_id=s.id')
            ->where(['t.employees_id'=>$this->id])
            ->groupBy('t.subdivisions_id')
            ->asArray()
            ->all();
        return $result;
    }
}

controllers/EmployeesController.php
<?php

namespace app\controllers;

use app\models\EmployeesFilterForm;
use app\models\Subdivisions;
use app\models\Terminals;
use app\modules\admin\models\Employees;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class EmployeesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'logout'],
                'rules' => [
                    [
                        'actions' => ['index', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * action Index.
     *
     * @return string
     */
    public function actionIndex()
    {
        $filter_form = new EmployeesFilterForm(); //model for form
        $query = Employees::find()->from('employees e'); //select Employees
        $subdivisions = [];
        if ($filter_form->load(Yii::$app->request->get())) { //if form is valid
            $query->where(['subdivisions_id' => Yii::$app->request->get('EmployeesFilterForm')['subdivisions_id']]);
            $subdivisions = Subdivisions::findOne(['id' => Yii::$app->request->get('EmployeesFilterForm')['subdivisions_id']]);
        }
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count()]); // pagination
        $models = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        return $this->render('index', [
            'models' => $models,
            'pages' => $pages,
            'filter_form' => $filter_form,
            'subdivisions' => $subdivisions
        ]);
    }


}

controllers/SubdivisionsController.php
<?php

namespace app\controllers;

use app\models\Subdivisions;
use app\models\Terminals;
use app\modules\admin\models\Employees;
use Yii;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class SubdivisionsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'logout'],
                'rules' => [
                    [
                        'actions' => ['index', 'logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * return Subdivisions for select2
     *
     * @param null $q
     * @param null $id
     * @return array
     */
    public function actionSearchSubdivisions($q = null, $id = null)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $out = ['results' => ['id' => '', 'text' => '']];
        if (!is_null($q)) {
            $data = Subdivisions::find()
                ->select(['id, CONCAT(`name`," ",`city`) AS text'])
                ->where(['like', 'LOWER(`name`)', (strtolower($q))])
                ->asArray()
                ->all(); //select Subdivisions
            $out['results'] = array_values($data);
        } elseif ($id > 0) {
            $out['results'] = ['id' => $id, 'text' => Subdivisions::findOne(['id' => $id])->name];
        }
        return $out;
    }

}

views/employees/index.php
<?php

use \yii\widgets\LinkPager;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use kartik\select2\Select2;
use yii\web\JsExpression;

/* @var $this yii\web\View */
/* @var $models \app\models\Employees */
/* @var $pages \yii\data\Pagination */
/* @var $filter_form \app\models\EmployeesFilterForm */

$this->title = 'Ответственые работники';

?>
<div class="site-index">
    <div><a href="/admin">ADMIN PANEL</a></div>
    <div class="row">
        <h3><?= $this->title ?></h3>

        <?php $form = ActiveForm::begin([
            'action'=>'/employees',
            'method' => 'get',
            'id' => 'filter-form',
            'fieldConfig' => [
                'template' => "<div class='col-md-12'>{label}</div><div class='row col-md-9'>\n<div class=\"col-md-12\">{input}</div>\n<div class=\"col-md-12\">{error}</div>\n</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ]); ?>

        <? $filter_form->subdivisions_id = !empty($subdivisions) ? $subdivisions->id : '' ?>
        <?= $form->field($filter_form, 'subdivisions_id')->widget(Select2::classname(), [
            'initValueText' => !empty($subdivisions) ? $subdivisions->name . ' ' . $subdivisions->city : '', // set the initial display text
            'pluginOptions' => [
                'allowClear' => true,
                'minimumInputLength' => 3,
                'language' => [
                    'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
                ],
                'ajax' => [
                    'url' => '/subdivisions/search-subdivisions',
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],
                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                'templateResult' => new JsExpression('function(city) { return city.text; }'),
                'templateSelection' => new JsExpression('function (city) { return city.text; }'),
            ],
        ]); ?>


        <div class="col-md-2">
            <?= Html::submitButton('Найти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>


        <?php ActiveForm::end(); ?>
        <table class="table table-striped">
            <thead>
            <th>ID</th>
            <th>Имя</th>
            <th>Подраздиление</th>
            <th>Количество терминалов</th>
            </thead>
            <tbody>

            <? foreach ($models as $v) { ?>
                <? /**
                 * @var \app\models\Employees $v
                 */
                ?>
                <tr>
                    <td><?= $v->id ?></td>
                    <td>
                        <?= $v->name ?>
                    </td>
                    <td>
                        <?= $v->subdivisions->name ?> - <?= $v->subdivisions->city ?>
                    </td>
                    <td>
                        <? foreach ($v->getSubdivisionsWithTerminalCount() as $t) { ?>
                            <div><?= $t['name'] ?> - <?= $t['c'] ?></div>
                        <? } ?>
                    </td>
                </tr>
            <? } ?>
            </tbody>
        </table>
    </div>

    <div class="text-center">
        <?= LinkPager::widget([
            'pagination' => $pages,
        ]); ?>
    </div>
</div>